[workspace]
members = [
  "iroha",
  "iroha_client",
  "iroha_client_cli",
  "iroha_crypto",
  "iroha_crypto_cli",
  "iroha_data_model",
  "iroha_dsl",
  "iroha_error",
  "iroha_error/iroha_error_macro",
  "iroha_http_server",
  "iroha_macro",
  "iroha_macro/iroha_derive",
  "iroha_network",
  "iroha_permissions_validators",
  "iroha_substrate",
  "iroha/test_network",
  "iroha_version",
  "iroha_version/iroha_version_derive",
  "iroha_config",
  "iroha_config/iroha_config_derive",
  "iroha_introspect",
  "iroha_introspect/iroha_introspect_derive",
  "iroha/docs",
]
